// Reusable personalised feed engine with configurable vertical source sets.
// This registry is the white-label boundary for selectable entities and feeds.

export type RegistryItemType =
  | "brand"
  | "model-platform"
  | "creator"
  | "source"
  | "topic"
  | "technology";

export type RegistryItem = {
  id: string;
  label: string;
  type: RegistryItemType;
  status?: "active" | "partial" | "placeholder";
  tag?: string;
  aliases?: string[];
  keywords?: string[];
  feedType?: "rss" | "youtube";
  feedEnabled?: boolean;
  url?: string;
  channelId?: string;
  relatedBrands?: string[];
};

export const registry = {
  brands: [
    {
      id: "bambu-lab",
      label: "Bambu Lab",
      type: "brand",
      tag: "Bambu",
      aliases: ["Bambu X1 Carbon", "Bambu P1S", "Bambu A1", "Bambu A1 Mini"],
      keywords: ["bambu", "x1 carbon", "p1s", "a1 mini", "bambu a1"],
    },
    {
      id: "prusa-research",
      label: "Prusa Research",
      type: "brand",
      tag: "Prusa",
      aliases: ["Prusa MK4S", "Prusa XL"],
      keywords: ["prusa", "mk4s", "prusa xl"],
    },
    {
      id: "creality",
      label: "Creality",
      type: "brand",
      tag: "Creality",
      aliases: ["Creality K1", "Creality K2 Plus"],
      keywords: ["creality", "k1", "k2 plus"],
    },
    {
      id: "elegoo",
      label: "Elegoo",
      type: "brand",
      tag: "Elegoo",
      keywords: ["elegoo"],
    },
    {
      id: "anycubic",
      label: "Anycubic",
      type: "brand",
      tag: "Anycubic",
      keywords: ["anycubic"],
    },
    {
      id: "flashforge",
      label: "Flashforge",
      type: "brand",
      tag: "Flashforge",
      keywords: ["flashforge"],
    },
    {
      id: "ultimaker",
      label: "UltiMaker",
      type: "brand",
      tag: "UltiMaker",
      keywords: ["ultimaker", "ulti maker"],
    },
    {
      id: "formlabs",
      label: "Formlabs",
      type: "brand",
      tag: "Formlabs",
      keywords: ["formlabs", "form 4", "form 3"],
    },
    {
      id: "markforged",
      label: "Markforged",
      type: "brand",
      tag: "Markforged",
      keywords: ["markforged", "mark forged"],
    },
    {
      id: "bigrep",
      label: "BigRep",
      type: "brand",
      tag: "BigRep",
      keywords: ["bigrep", "big rep"],
    },
    {
      id: "raise3d",
      label: "Raise3D",
      type: "brand",
      tag: "Raise3D",
      keywords: ["raise3d", "raise 3d"],
    },
    {
      id: "bcn3d",
      label: "BCN3D",
      type: "brand",
      tag: "BCN3D",
      keywords: ["bcn3d", "bcn 3d"],
    },
    {
      id: "wasp",
      label: "WASP",
      type: "brand",
      tag: "WASP",
      keywords: ["wasp", "world's advanced saving project"],
    },
    {
      id: "stratasys",
      label: "Stratasys",
      type: "brand",
      tag: "Stratasys",
      keywords: ["stratasys"],
    },
    {
      id: "shining3d",
      label: "Shining3D",
      type: "brand",
      tag: "Shining3D",
      keywords: ["shining3d", "shining 3d"],
    },
    {
      id: "snapmaker",
      label: "Snapmaker",
      type: "brand",
      tag: "Snapmaker",
      keywords: ["snapmaker"],
    },
  ],
  modelPlatforms: [
    {
      id: "printables",
      label: "Printables",
      type: "model-platform",
      tag: "Printables",
      keywords: ["printables"],
    },
    {
      id: "makerworld",
      label: "MakerWorld",
      type: "model-platform",
      tag: "MakerWorld",
      keywords: ["makerworld", "maker world"],
    },
    {
      id: "thingiverse",
      label: "Thingiverse",
      type: "model-platform",
      tag: "Thingiverse",
      keywords: ["thingiverse"],
    },
    {
      id: "thangs",
      label: "Thangs",
      type: "model-platform",
      tag: "Thangs",
      keywords: ["thangs"],
    },
    {
      id: "cults3d",
      label: "Cults3D",
      type: "model-platform",
      tag: "Cults3D",
      keywords: ["cults3d", "cults"],
    },
    {
      id: "myminifactory",
      label: "MyMiniFactory",
      type: "model-platform",
      tag: "MyMiniFactory",
      keywords: ["myminifactory", "my mini factory"],
    },
  ],
  creators: [
    {
      id: "makers-muse",
      label: "Maker's Muse",
      type: "creator",
      status: "partial",
      tag: "Maker's Muse",
      feedType: "youtube",
      feedEnabled: true,
      channelId: "CHANNEL_ID_TODO_MAKERS_MUSE",
      keywords: ["maker's muse", "makers muse"],
    },
    {
      id: "cnc-kitchen",
      label: "CNC Kitchen",
      type: "creator",
      status: "partial",
      tag: "CNC Kitchen",
      feedType: "youtube",
      feedEnabled: true,
      channelId: "CHANNEL_ID_TODO_CNC_KITCHEN",
      keywords: ["cnc kitchen"],
    },
    {
      id: "3d-printing-nerd",
      label: "3D Printing Nerd",
      type: "creator",
      status: "partial",
      tag: "3D Printing Nerd",
      feedType: "youtube",
      feedEnabled: true,
      channelId: "CHANNEL_ID_TODO_3D_PRINTING_NERD",
      keywords: ["3d printing nerd"],
    },
    {
      id: "teaching-tech",
      label: "Teaching Tech",
      type: "creator",
      status: "partial",
      tag: "Teaching Tech",
      feedType: "youtube",
      feedEnabled: true,
      channelId: "CHANNEL_ID_TODO_TEACHING_TECH",
      keywords: ["teaching tech"],
    },
    {
      id: "thomas-sanladerer",
      label: "Thomas Sanladerer",
      type: "creator",
      status: "partial",
      tag: "Thomas Sanladerer",
      feedType: "youtube",
      feedEnabled: true,
      channelId: "CHANNEL_ID_TODO_THOMAS_SANLADERER",
      keywords: ["thomas sanladerer", "toms3d"],
    },
    {
      id: "aurora-tech",
      label: "Aurora Tech",
      type: "creator",
      status: "partial",
      tag: "Aurora Tech",
      feedType: "youtube",
      feedEnabled: true,
      channelId: "CHANNEL_ID_TODO_AURORA_TECH",
      keywords: ["aurora tech"],
    },
    {
      id: "3d-revolution",
      label: "3D Revolution",
      type: "creator",
      status: "placeholder",
      tag: "3D Revolution",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_3D_REVOLUTION",
      keywords: ["3d revolution"],
    },
    {
      id: "chep",
      label: "CHEP",
      type: "creator",
      status: "placeholder",
      tag: "CHEP",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_CHEP",
      keywords: ["chep", "filament friday"],
    },
    {
      id: "made-with-layers",
      label: "Made With Layers",
      type: "creator",
      status: "placeholder",
      tag: "Made With Layers",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_MADE_WITH_LAYERS",
      keywords: ["made with layers"],
    },
    {
      id: "lost-in-tech",
      label: "Lost In Tech",
      type: "creator",
      status: "placeholder",
      tag: "Lost In Tech",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_LOST_IN_TECH",
      keywords: ["lost in tech"],
    },
    {
      id: "frankly-built",
      label: "Frankly Built",
      type: "creator",
      status: "placeholder",
      tag: "Frankly Built",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_FRANKLY_BUILT",
      keywords: ["frankly built"],
    },
    {
      id: "uncle-jessy",
      label: "Uncle Jessy",
      type: "creator",
      status: "placeholder",
      tag: "Uncle Jessy",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_UNCLE_JESSY",
      keywords: ["uncle jessy"],
    },
    {
      id: "bv3d",
      label: "BV3D",
      type: "creator",
      status: "placeholder",
      tag: "BV3D",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_BV3D",
      keywords: ["bv3d"],
    },
    {
      id: "modbot",
      label: "ModBot",
      type: "creator",
      status: "placeholder",
      tag: "ModBot",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_MODBOT",
      keywords: ["modbot", "mod bot"],
    },
    {
      id: "maker-tales",
      label: "Maker Tales",
      type: "creator",
      status: "placeholder",
      tag: "Maker Tales",
      feedType: "youtube",
      feedEnabled: false,
      channelId: "CHANNEL_ID_TODO_MAKER_TALES",
      keywords: ["maker tales"],
    },
  ],
  sources: [
    {
      id: "3d-printing-industry",
      label: "3D Printing Industry",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://3dprintingindustry.com/feed/",
    },
    {
      id: "3dprint-com",
      label: "3DPrint.com",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://3dprint.com/feed/",
    },
    {
      id: "all3dp",
      label: "All3DP News",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://all3dp.com/feed/",
    },
    {
      id: "fabbaloo",
      label: "Fabbaloo",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "tct-magazine",
      label: "TCT Magazine",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://www.tctmagazine.com/rss/",
    },
    {
      id: "develop3d",
      label: "DEVELOP3D",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://develop3d.com/feed/",
    },
    {
      id: "3dprinting-com",
      label: "3DPrinting.com",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://3dprinting.com/feed/",
    },
    {
      id: "3dsourced",
      label: "3DSourced",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://www.3dsourced.com/feed/",
    },
    {
      id: "3d-insider",
      label: "3D Insider",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://3dinsider.com/feed/",
    },
    {
      id: "3ders-org",
      label: "3ders.org",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "toms-3d",
      label: "TOM's 3D",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "total-3d-printing",
      label: "Total 3D Printing",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "prusa-blog",
      label: "Prusa Blog",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://blog.prusa3d.com/feed/",
      relatedBrands: ["prusa-research"],
    },
    {
      id: "bambu-lab-blog",
      label: "Bambu Lab Blog",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://blog.bambulab.com/feed/",
      relatedBrands: ["bambu-lab"],
    },
    {
      id: "creality-blog",
      label: "Creality Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
      relatedBrands: ["creality"],
    },
    {
      id: "ultimaker-blog",
      label: "UltiMaker Blog",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://ultimaker.com/blog/feed/",
      relatedBrands: ["ultimaker"],
    },
    {
      id: "formlabs-blog",
      label: "Formlabs Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
      relatedBrands: ["formlabs"],
    },
    {
      id: "markforged-blog",
      label: "Markforged Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
      relatedBrands: ["markforged"],
    },
    {
      id: "bigrep-blog",
      label: "BigRep Blog",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://bigrep.com/feed/",
      relatedBrands: ["bigrep"],
    },
    {
      id: "wasp-blog",
      label: "WASP Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
      relatedBrands: ["wasp"],
    },
    {
      id: "stratasys-blog",
      label: "Stratasys Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
      relatedBrands: ["stratasys"],
    },
    {
      id: "raise3d-blog",
      label: "Raise3D Blog",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://www.raise3d.com/feed/",
      relatedBrands: ["raise3d"],
    },
    {
      id: "bcn3d-blog",
      label: "BCN3D Blog",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://www.bcn3d.com/feed/",
      relatedBrands: ["bcn3d"],
    },
    {
      id: "matterhackers",
      label: "MatterHackers",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "3dprintbeginner",
      label: "3DPrintBeginner",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://3dprintbeginner.com/feed/",
    },
    {
      id: "3dwithus",
      label: "3DWithUs",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://3dwithus.com/feed",
    },
    {
      id: "treatstock-blog",
      label: "Treatstock Blog",
      type: "source",
      status: "active",
      feedType: "rss",
      url: "https://www.treatstock.com/blog/rss",
    },
    {
      id: "cults-blog",
      label: "Cults Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "shapeways-blog",
      label: "Shapeways Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "i-materialise-blog",
      label: "i.materialise Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
    {
      id: "simplify3d-blog",
      label: "Simplify3D Blog",
      type: "source",
      status: "placeholder",
      feedType: "rss",
      feedEnabled: false,
    },
  ],
  topics: [
    {
      id: "new-printers",
      label: "New Printers",
      type: "topic",
      tag: "New Printers",
      keywords: ["new printer", "launch", "announces", "released", "debut"],
    },
    {
      id: "reviews",
      label: "Reviews",
      type: "topic",
      tag: "Reviews",
      keywords: ["review", "reviews", "tested", "hands-on", "benchmark"],
    },
    {
      id: "firmware-updates",
      label: "Firmware Updates",
      type: "topic",
      tag: "Firmware",
      keywords: ["firmware", "software update", "input shaping"],
    },
    {
      id: "3d-models-designs",
      label: "3D Models / Designs",
      type: "topic",
      tag: "Models",
      keywords: ["model", "models", "design", "printables", "makerworld"],
    },
    {
      id: "filament-materials",
      label: "Filament & Materials",
      type: "topic",
      tag: "Materials",
      keywords: ["material", "materials", "filament", "pla", "petg", "nylon"],
    },
    {
      id: "accessories",
      label: "Accessories",
      type: "topic",
      tag: "Accessories",
      keywords: ["accessory", "accessories", "upgrade", "hotend", "build plate"],
    },
    {
      id: "deals-discounts",
      label: "Deals & Discounts",
      type: "topic",
      tag: "Deals",
      keywords: ["deal", "deals", "discount", "sale", "bundle", "coupon"],
    },
    {
      id: "tutorials-guides",
      label: "Tutorials & Guides",
      type: "topic",
      tag: "Tutorials",
      keywords: ["tutorial", "tutorials", "guide", "how to", "calibration"],
    },
  ],
  technologies: [
    {
      id: "fdm-fff",
      label: "FDM / FFF",
      type: "technology",
      tag: "FDM",
      keywords: ["fdm", "fff", "filament"],
    },
    {
      id: "resin",
      label: "Resin",
      type: "technology",
      tag: "Resin",
      keywords: ["resin", "sla", "msla", "dlp"],
    },
    {
      id: "sls-mjf",
      label: "SLS / MJF",
      type: "technology",
      tag: "SLS",
      keywords: ["sls", "mjf", "powder bed"],
    },
    {
      id: "industrial-professional",
      label: "Industrial / Professional",
      type: "technology",
      tag: "Industrial",
      keywords: ["industrial", "professional", "production", "service bureau"],
    },
  ],
} as const satisfies Record<string, readonly RegistryItem[]>;

export const selectableSources = registry.sources as readonly RegistryItem[];

export const activeFeedSources = [
  ...(registry.sources as readonly RegistryItem[]).filter(
    (source) => source.feedEnabled !== false && source.url,
  ),
  ...(registry.creators as readonly RegistryItem[]).filter(
    (creator) =>
      creator.feedType === "youtube" &&
      creator.feedEnabled !== false &&
      creator.channelId,
  ),
];
