insert into verticals (
  id,
  organisation_id,
  name,
  slug,
  description,
  status,
  visibility,
  strategy,
  sponsor_id,
  public_url,
  publication_name,
  publication_description,
  publication_type,
  default_collections,
  hostname,
  publication_status,
  auto_fetch_enabled,
  show_in_discover,
  show_newsletter_signup,
  show_feedback,
  primary_colour
) values (
  '66666666-6666-4666-8666-666666666666',
  '11111111-1111-4111-8111-111111111111',
  'MyLiverpoolNews',
  'myliverpoolnews',
  'Proof-of-concept place-based publication for Liverpool readers.',
  'active',
  'demo',
  'community',
  null,
  '/publications/myliverpoolnews',
  'MyLiverpoolNews',
  'Local news, business, transport, culture, events, and city updates for Liverpool.',
  'place',
  '["News","Business","Transport","Planning","Property","Culture","Events","Sport","Universities","Community","Waterfront"]'::jsonb,
  'myliverpoolnews.mynewsnetwork.uk',
  'draft',
  true,
  true,
  true,
  true,
  '#dc2626'
)
on conflict (slug) do update set
  organisation_id = excluded.organisation_id,
  name = excluded.name,
  description = excluded.description,
  status = excluded.status,
  visibility = excluded.visibility,
  strategy = excluded.strategy,
  sponsor_id = excluded.sponsor_id,
  public_url = excluded.public_url,
  publication_name = excluded.publication_name,
  publication_description = excluded.publication_description,
  publication_type = excluded.publication_type,
  default_collections = excluded.default_collections,
  hostname = excluded.hostname,
  publication_status = excluded.publication_status,
  auto_fetch_enabled = excluded.auto_fetch_enabled,
  show_in_discover = excluded.show_in_discover,
  show_newsletter_signup = excluded.show_newsletter_signup,
  show_feedback = excluded.show_feedback,
  primary_colour = excluded.primary_colour,
  updated_at = now();
