insert into verticals (
  id,
  organisation_id,
  name,
  slug,
  description,
  status,
  visibility,
  strategy,
  sponsor_id,
  public_url,
  publication_name,
  publication_description,
  publication_type,
  default_collections,
  hostname,
  publication_status,
  auto_fetch_enabled,
  show_in_discover,
  show_newsletter_signup,
  show_feedback,
  primary_colour
) values (
  '77777777-7777-4777-8777-777777777777',
  '11111111-1111-4111-8111-111111111111',
  'MyPrestonNews',
  'myprestonnews',
  'Proof-of-concept place-based publication for Preston readers.',
  'active',
  'demo',
  'community',
  null,
  '/publications/myprestonnews',
  'MyPrestonNews',
  'Local news, events, community updates, business, transport, sport, and city life for Preston.',
  'place',
  '["News","Events","Community","Business","Transport","Sport","Universities","Food & Drink","Property","Videos"]'::jsonb,
  'myprestonnews.mynewsnetwork.uk',
  'draft',
  true,
  true,
  true,
  true,
  '#475569'
)
on conflict (slug) do update set
  organisation_id = excluded.organisation_id,
  name = excluded.name,
  description = excluded.description,
  status = excluded.status,
  visibility = excluded.visibility,
  strategy = excluded.strategy,
  sponsor_id = excluded.sponsor_id,
  public_url = excluded.public_url,
  publication_name = excluded.publication_name,
  publication_description = excluded.publication_description,
  publication_type = excluded.publication_type,
  default_collections = excluded.default_collections,
  hostname = excluded.hostname,
  publication_status = excluded.publication_status,
  auto_fetch_enabled = excluded.auto_fetch_enabled,
  show_in_discover = excluded.show_in_discover,
  show_newsletter_signup = excluded.show_newsletter_signup,
  show_feedback = excluded.show_feedback,
  primary_colour = excluded.primary_colour,
  updated_at = now();
